name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: windows-latest
    env:
      CC: clang
      CFLAGS: -Werror
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20.0'

    - name: Install MinGW manually
      run: |
          choco install mingw -y
        
    - name: Build
      run: |
        go build -v 

    - name: Test
      run: go test -v ./...

    # Add an upload-artifact step here if you need to pass built files to the "release" job

  release:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: my-artifact

      # ...add steps to create a GitHub release...

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        with:
          name: my-artifact.zip
          asset_path: path/to/downloaded/artifact
          url: ${{ steps.create_release.outputs.upload_url }}
